"""empty message

Revision ID: 555f0e2a9f6e
Revises: ad90551419d3
Create Date: 2017-02-13 22:11:06.325123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555f0e2a9f6e'
down_revision = 'ad90551419d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
